// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	paymentFieldNames          = builder.RawFieldNames(&Payment{})
	paymentRows                = strings.Join(paymentFieldNames, ",")
	paymentRowsExpectAutoSet   = strings.Join(stringx.Remove(paymentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	paymentRowsWithPlaceHolder = strings.Join(stringx.Remove(paymentFieldNames, "`payment_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	paymentModel interface {
		Insert(ctx context.Context, data *Payment) (sql.Result, error)
		FindOne(ctx context.Context, paymentId int64) (*Payment, error)
		Update(ctx context.Context, data *Payment) error
		Delete(ctx context.Context, paymentId int64) error
	}

	defaultPaymentModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Payment struct {
		PaymentId     int64         `db:"payment_id"`
		PaymentMethod sql.NullInt64 `db:"payment_method"`
		Deposit       sql.NullInt64 `db:"deposit"`
		AmountOwed    sql.NullInt64 `db:"amount_owed"`
	}
)

func newPaymentModel(conn sqlx.SqlConn) *defaultPaymentModel {
	return &defaultPaymentModel{
		conn:  conn,
		table: "`payment`",
	}
}

func (m *defaultPaymentModel) Delete(ctx context.Context, paymentId int64) error {
	query := fmt.Sprintf("delete from %s where `payment_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, paymentId)
	return err
}

func (m *defaultPaymentModel) FindOne(ctx context.Context, paymentId int64) (*Payment, error) {
	query := fmt.Sprintf("select %s from %s where `payment_id` = ? limit 1", paymentRows, m.table)
	var resp Payment
	err := m.conn.QueryRowCtx(ctx, &resp, query, paymentId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPaymentModel) Insert(ctx context.Context, data *Payment) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, paymentRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PaymentId, data.PaymentMethod, data.Deposit, data.AmountOwed)
	return ret, err
}

func (m *defaultPaymentModel) Update(ctx context.Context, data *Payment) error {
	query := fmt.Sprintf("update %s set %s where `payment_id` = ?", m.table, paymentRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.PaymentMethod, data.Deposit, data.AmountOwed, data.PaymentId)
	return err
}

func (m *defaultPaymentModel) tableName() string {
	return m.table
}
