// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"tourBooking/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cors},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/users/registation",
					Handler: CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/login",
					Handler: UserLoginHandler(serverCtx),
				},
			}...,
		),
	)
}
